74 symbol追加、API仕様変更対応
amashita/GmoCoin pull request #75
Opened 2021-07-18 02:30 UTC by makotookamura

2021-07-18 13:21 UTC, amashita requested changes

2021-07-18 13:21 UTC, amashita commented on gmocoin/private/dto.py
> +    def __init__(self, actual_profit_loss: Decimal, available_amount: Decimal, margin: Decimal, margin_call_status: MarginCallStatus, margin_ratio: Decimal, profit_loss: Decimal) -> None:
7/18段階でテストを実行すると、`margin_ratio`が返却されていないため、エラーとなりますので、  
返却されない場合デフォルト値-1としていただきたいです。

```suggestion
    def __init__(self, actual_profit_loss: Decimal, available_amount: Decimal, margin: Decimal, margin_call_status: MarginCallStatus, profit_loss: Decimal, margin_ratio: Decimal = -1) -> None:
```

2021-07-20 04:42 UTC, makotookamura commented on gmocoin/private/dto.py
> +    def __init__(self, actual_profit_loss: Decimal, available_amount: Decimal, margin: Decimal, margin_call_status: MarginCallStatus, margin_ratio: Decimal, profit_loss: Decimal) -> None:
ご確認ありがとうございます。Commitさせていただきました。

2021-07-20 12:47 UTC, amashita approved these changes
LGTMです！
対応ありがとうございます！

2021-07-20 12:48 UTC, merged